esphome:
  name: "watermeter8266"

esp8266:
  board: esp01_1m

logger:

api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.197
    gateway: 192.168.0.1
    subnet: 255.255.255.0


  ap:
    ssid: "Esphome-Web-D88A0F"
    password: "ACNHjFnYVVhF"

captive_portal:

sensor:
  - platform: homeassistant
    id: temp
    entity_id: sensor.climate_termo

font:
  - file: 'slkscr.ttf'
    id: font1
    size: 14

  - file: 'arial.ttf'
    id: font2
    size: 12

spi:
  clk_pin: GPIO16
  mosi_pin: GPIO5

display:
  - platform: ssd1306_spi
    model: "SSD1306 128x64"
    cs_pin: GPIO4
    dc_pin: GPIO0
    reset_pin: GPIO2
    lambda: |-
      it.printf(0, 0, id(font1), "%.1f", id(temp).state);


      - id: page4 # Office Temp / Hum
        lambda: |-
          it.printf(0, 0, id(font1), "%.1f", id(officetemp).state);
          it.printf(0, 16, id(font1), "%.1f", id(officehumid).state);


    