#Счетчик Бентар СГВ-15Д

esphome:
  name: "watermeter8266"

esp8266:
  board: esp01_1m
  restore_from_flash: true
  
preferences:
  flash_write_interval: 60min

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.197
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-D88A0F"
    password: "ACNHjFnYVVhF"

captive_portal:

# Water
sensor:
  - platform: pulse_counter
    id: water
    pin: GPIO14
    unit_of_measurement: 'm3/min'
    accuracy_decimals: 1
    name: 'Water'
    filters: 
      - multiply: 0.01

  - platform: integration
    device_class: water
    state_class: total
    name: "Total water"
    id: totalwater
    sensor: water
    time_unit: min
    accuracy_decimals: 3
    restore: true
    filters:
      - offset: 1.481

font:
  - file: 'slkscr.ttf'
    id: font1
    size: 12

  - file: 'arial.ttf'
    id: font2
    size: 12

  - file: 'roboto-medium.ttf'
    id: font3
    size: 12
    glyphs: |-
      !"%()+=,-_.:°0123456789АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧЩЬЫЪЭЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ абвгдеёжзийклмнопрстуфхцчщьыъэюяabcdefghijklmnopqrstuvwxyz'éèàòùç/&ôœìïöñ

spi:
  clk_pin: GPIO16
  mosi_pin: GPIO5

display:
  - platform: ssd1306_spi
    model: "SSD1306 128x64"
    cs_pin: GPIO4
    dc_pin: GPIO0
    reset_pin: GPIO2
    lambda: |-
      it.printf(0, 0, id(font3), "Всего: %1f", id(totalwater).state);
      it.printf(0, 16, id(font3), "В минуту: %1f", id(water).state);
